### ISSUE TITLE
Amazon Appstore not identified

### ISSUE THREAD

**Issue by BarnburnerB** [onepf/OpenIAB#482]
I can't get OpenIAB v0.9.8.6 to identify the Amazon Appstore.  I'm testing locally and installing the apk using the adb install -i com.amazon.venezia <apk path> technique. Here are my logs

05-01 19:31:43.899  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ checkOptions() Options={availableStores=[], availableStoreNames=[com.amazon.apps], preferredStoreNames=[], discoveryTimeoutMs=0, checkInventory=false, checkInventoryTimeoutMs=0, verifyMode=0, storeSearchStrategy=0, storeKeys={}, samsungCertificationRequestCode=899}
05-01 19:31:43.899  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ checkGoogle() verify mode = 0
05-01 19:31:43.899  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ checkGoogle() google key available = false
05-01 19:31:43.899  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ checkGoogle() ignoring GooglePlay wrapper.
05-01 19:31:43.899  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ checkSamsung() activity = null
05-01 19:31:43.899  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ checkSamsung() ignoring Samsung wrapper
05-01 19:31:43.909  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ hasRequestedPermission() is false for com.nokia.payment.BILLING
05-01 19:31:43.909  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ checkNokia() has permission = false
05-01 19:31:43.909  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ checkNokia() ignoring Nokia wrapper
05-01 19:31:43.909  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ checkFortumo() fortumo sdk available: false
05-01 19:31:43.909  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ checkFortumo() fortumo billing required: false
05-01 19:31:43.909  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ checkFortumo() ignoring fortumo wrapper.
05-01 19:31:43.909  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ checkAmazon() amazon sdk available: true
05-01 19:31:43.909  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ startSetup() options = Options={availableStores=[], availableStoreNames=[com.amazon.apps], preferredStoreNames=[], discoveryTimeoutMs=0, checkInventory=false, checkInventoryTimeoutMs=0, verifyMode=0, storeSearchStrategy=0, storeKeys={}, samsungCertificationRequestCode=899}
05-01 19:31:43.929  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ setupWithStrategy() store search strategy = 0
05-01 19:31:43.929  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ setupWithStrategy() package name = com.barnburner.freebeez.android
05-01 19:31:43.939  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ setupWithStrategy() package installer = com.amazon.venezia
05-01 19:31:43.939  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ packageInstalled() is false for com.amazon.venezia
05-01 19:31:43.939  30603-30603/com.barnburner.freebeez.android D/OpenIAB﹕ finishSetup() === SETUP DONE === result: IabResult: 3, No suitable appstore was found (response: 3:Billing Unavailable) Appstore: null

The logs show that it's identifying the packageInstaller as com.amazon.venezia, but when it reaches Utils.packageInstalled(...) it determines that the package is not installed.

**Comment by RomanZhilich** [comment]
Looks like Amazon released new store app with different package.
I'll see what it can do to fix it, meanwhile Amazon should work [here](https://github.com/onepf/OPFIab). I do realize the inconvenience (API is different) but this is something to consider.

**Comment by BarnburnerB** [comment]
Thanks.  Besides potentially solving this issue, what are the advantages of OPFIab?

**Comment by RomanZhilich** [comment]
I'll be gradually adding more info to OPFIab wiki and README to better explain its capabilities.

In short: OpenIAB suffers from legacy architecture of Google's TrivialDrive example with IabHelper from which it was pretty much copy-pasted. With addition of new supported appstores and unfinished concept of OpenStores it became increasingly more difficult to support.
As you might've noticed it also suffers from all-features-in-one-heap issue. This very issue is caused by Amazon changing something on their side and now library must be modified to adopt those changes.

OPFIab is an attempt to rethink what universal billing library should've been from the start without Google's legacy. Most notable results:
* First and foremost - moduled architecture. Changes made by Amazon should only effect Amazon module etc.
* Straightforward configuration. Library should be setup once and preferably form `Application#onCreate` since this is the only code guaranteed to be executed if app was started from `BroadcaseReceiver`.
* Simple memory leak free API. OPFIab allows to define global `BillingListener` and handle all non-ui related changes in one place (SharedPreferences, DataBase, ContentProvider etc.)
* Overall better quality code with more android-friendly architecture and less concurrency pitfalls.

**Comment by Lakedaemon** [comment]
You should copy and past this in the wiki of your new project. 
It pretty much answers everything I was wondering about OPFIab.
I'll be watching this new library and integrate it as soon as it is production ready in my apps.
